# -*- coding: utf-8 -*-
"""openweather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a9PfUPek8z_X1GU6xCPkoqXuTmXObfcd
"""

import os
import requests
API_KEY = os.environ.get('API_KEY') #'79516e2aea37c0be1937220707cffd74'
LATITUDE = os.environ.get('LAT') #'31.2504'
LONGITUDE = os.environ.get('LONG') #'-99.2506'

def get_weather(LATITUDE, LONGITUDE, API_KEY):
    url = f'https://api.openweathermap.org/data/2.5/weather?lat={LATITUDE}&lon={LONGITUDE}&appid={API_KEY}&units=metric'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        temperature = data['main']['temp']
        weather_description = data['weather'][0]['description']
        feeled_temp = data['main']['feels_like']
        wind_speed = data['wind']['speed']

        return f'Temperature: {temperature}°C\nFeels like: {feeled_temp}°C\nWind speed: {wind_speed} km/h\nWeather: {weather_description}'
    else:
        return 'Error getting weather data'

print(get_weather(LATITUDE, LONGITUDE, API_KEY))