name: Build and publish Docker image



on:
 push:
 branches: [ main ]


jobs:
 build-and-publish:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout source code
 uses: actions/checkout@v2


 - name: Build Docker image
 run: docker build -t sarankansivananthan/mu-weather-app-2 .



 - name: Login to Docker Hub
 uses: docker/login-action@v1
 with:
 username: ${{ secrets.DOCKERHUB_USERNAME }}
 password: ${{ secrets.DOCKERHUB_TOKEN }}


 - name: Push Docker image to Docker Hub
 uses: docker/build-push-action@v2
 with:
 context: .
 push: true
 tags: sarankansivananthan/mu-weather-app-2

 - name: run weather test
 run: docker run --env LAT="31.2504" --env LONG="-99.2506" --env API_KEY=9e518e1b1b5a0288918557d8a16255bb stang94/tp2:latest